---
spring:
  application:
    name: "deviceapi"
  jpa:
    hibernate:
      ddl-auto: "validate"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: "org.hibernate.dialect.PostgreSQLDialect"
  datasource:
    driverClassName: "org.postgresql.Driver"
    url: "jdbc:postgresql://localhost:5432/deviceapi"
    username: "username"
    password: "password"
  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false
